#
#	Copyright 2024 James Burlingame
#
#	Licensed under the Apache License, Version 2.0 (the "License");
#	you may not use this file except in compliance with the License.
#	You may obtain a copy of the License at
#
#	    http://www.apache.org/licenses/LICENSE-2.0
#
#	Unless required by applicable law or agreed to in writing, software
#	distributed under the License is distributed on an "AS IS" BASIS,
#	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#	See the License for the specific language governing permissions and
#	limitations under the License.
#

Z80TOOLS_TARGET_DIR = /opt/z80tools
PREFIX = $(Z80TOOLS_TARGET_DIR)
BINDIR = $(PREFIX)/bin

INSTALL = install

DEBUG = -g
OPTIMIZE = -O2
COPTIONS = -Wall -Wextra -std=gnu99

CFLAGS = $(DEBUG) $(OPTIMIZE) $(COPTIONS)

all: intel-hex-loader

install: all
	$(INSTALL) -d $(BINDIR)
	$(INSTALL) -m 755 intel-hex-loader $(BINDIR)

clean:
	$(RM) intel-hex-loader
	$(RM) -r intel-hex-loader.dSYM

.PHONY: all clean check install
